### ISSUE TITLE
Component tarjeta event3

### ISSUE THREAD

**Issue by Big-Lolo** [LleidaHack/LleidaHackBackend#222]
Aquesta component està mal dissenyada. No compleix amb els estàndard de mides indicades al Figma, està fet amb px, per tant, no manté el disseny responsive i està fet amb posicions absolutes, cosa que en tractar entre components, es poden sobreposar, tal com em succeeix.
A més, la imatge no té un estil cover, cosa que fa que aquesta no mantingui la relació d'aspecte.

Revisar les altres components per si succeeix el mateix

**Comment by tonlls** [comment]
@Big-Lolo aixo es de front suposo xd
